workspace = { }

[package]
name = "simple-rust-bundler"
version = "0.0.1"
authors = [
  "Masato Yuna <masato.yuna@gmail.com>",
  "George Burton <burtonageo@gmail.com>",
  "Tauri Programme within The Commons Conservancy"
]
categories = [ "command-line-utilities", "development-tools::cargo-plugins" ]
license = "Apache-2.0 OR MIT"
keywords = []
repository = "https://github.com/generalworksinc/simple-rust-bundler.git"
description = "rust bundle tool from tauri bundler fork"
edition = "2021"
rust-version = "1.60"
exclude = [ "CHANGELOG.md", "/target", "rustfmt.toml" ]

[dependencies]
tauri-utils = { version = "1.2.1", path = "../../core/tauri-utils", features = [ "resources" ] }
image = "0.24.5"
libflate = "1.2"
anyhow = "1.0"
thiserror = "1.0"
serde_json = "1.0"
serde = { version = "1.0", features = [ "derive" ] }
strsim = "0.10.0"
tar = "0.4.38"
walkdir = "2"
handlebars = "4.3"
tempfile = "3.3.0"
log = { version = "0.4.17", features = [ "kv_unstable" ] }
dirs-next = "2.0"
encoding_rs = "0.8"
os_pipe = "1"

# dependencies for Windows targets
attohttpc = "0.24"
hex = "0.4"
semver = "1"
sha1 = "0.10"
sha2 = "0.10"
zip = "0.6"

# dependencies for code signing on Windows hosts
[target."cfg(target_os = \"windows\")".dependencies]
uuid = { version = "1", features = [ "v4", "v5" ] }
bitness = "0.4"
winreg = "0.10" # Can only be compiled for Windows hosts
glob = "0.3"


[target."cfg(target_os = \"macos\")".dependencies]
icns = { package = "tauri-icns", version = "0.1" }
time = { version = "0.3", features = [ "formatting" ] }
plist = "1"

[target."cfg(any(target_os = \"macos\", target_os = \"windows\"))".dependencies]
regex = "1"

[target."cfg(target_os = \"linux\")".dependencies]
heck = "0.4"
ar = "0.9.0"
md5 = "0.7.0"

[lib]
name = "tauri_bundler"
path = "src/lib.rs"
